In [4]:
import pandas as pd

In [10]:
df = pd.read_csv('archive/Automated_Traffic_Volume_Counts.csv', nrows = 5)

In [12]:
df.head()

,RequestID,Boro,Yr,M,D,HH,MM,Vol,SegmentID,WktGeom,street,fromSt,toSt,Direction
0,20856,Queens,2015,6,23,23,30,9,171896,POINT (1052296.600156678 199785.26932711253),94 AVENUE,207 Street,Francis Lewis Boulevard,WB
1,21231,Staten Island,2015,9,14,4,15,6,9896,POINT (942668.0589509147 171441.21296926),RICHMOND TERRACE,Wright Avenue,Emeric Court,WB
2,29279,Bronx,2017,10,19,4,30,85,77817,POINT (1016508.0034050211 235221.59092266942),HUNTS POINT AVENUE,Whittier Street,Randall Avenue,NB
3,27019,Brooklyn,2017,11,7,18,30,168,188023,POINT (992925.4316054962 184116.82855457635),FLATBUSH AVENUE,Brighton Line,Brighton Line,NB
4,26734,Manhattan,2017,11,3,22,0,355,137516,POINT (1004175.9505178436 247779.63624949602),WASHINGTON BRIDGE,Harlem River Shoreline,Harlem River Shoreline,EB

In [15]:
df.columns.tolist()

['RequestID',
 'Boro',
 'Yr',
 'M',
 'D',
 'HH',
 'MM',
 'Vol',
 'SegmentID',
 'WktGeom',
 'street',
 'fromSt',
 'toSt',
 'Direction']

In [16]:
# تحديد الأعمدة المطلوبة بناءً على تحليلنا
selected_columns = ['Boro', 'Yr', 'M', 'D', 'HH', 'MM', 'Vol', 'SegmentID', 'WktGeom', 'Direction']

# تصفية الداتا
df_traffic_filtered = df[selected_columns].copy()

# عرض أول بضع صفوف للتأكد
print(df_traffic_filtered.head())
print(f"عدد الأعمدة بعد التصفية: {df_traffic_filtered.shape[1]}")

            Boro    Yr   M   D  HH  MM  Vol  SegmentID  \
0         Queens  2015   6  23  23  30    9     171896
1  Staten Island  2015   9  14   4  15    6       9896
2          Bronx  2017  10  19   4  30   85      77817
3       Brooklyn  2017  11   7  18  30  168     188023
4      Manhattan  2017  11   3  22   0  355     137516

                                         WktGeom Direction
0   POINT (1052296.600156678 199785.26932711253)        WB
1      POINT (942668.0589509147 171441.21296926)        WB
2  POINT (1016508.0034050211 235221.59092266942)        NB
3   POINT (992925.4316054962 184116.82855457635)        NB
4  POINT (1004175.9505178436 247779.63624949602)        EB
عدد الأعمدة بعد التصفية: 10

In [20]:
df.head()

,Boro,Yr,M,D,HH,MM,Vol,SegmentID,WktGeom,Direction
0,Queens,2015,6,23,23,30,9,171896,POINT (1052296.600156678 199785.26932711253),WB
1,Staten Island,2015,9,14,4,15,6,9896,POINT (942668.0589509147 171441.21296926),WB
2,Bronx,2017,10,19,4,30,85,77817,POINT (1016508.0034050211 235221.59092266942),NB
3,Brooklyn,2017,11,7,18,30,168,188023,POINT (992925.4316054962 184116.82855457635),NB
4,Manhattan,2017,11,3,22,0,355,137516,POINT (1004175.9505178436 247779.63624949602),EB

In [23]:
import pandas as pd

# 1. مسار الملف الأصلي
input_file = 'archive/Automated_Traffic_Volume_Counts.csv'

# 2. قراءة كل الأعمدة (بدون تحديد usecols) مع جلب أول 5 صفوف فقط (nrows=5)
df_all_cols_sample = pd.read_csv(input_file, nrows=5)

# 3. حفظ الناتج في ملف جديد
output_file = 'nyc_all_features_first_5_rows.csv'
df_all_cols_sample.to_csv(output_file, index=False)

print(f"✅ تم بنجاح! تم أخذ كل الأعمدة مع أول 5 صفوف فقط وحفظها في: '{output_file}'")

# طباعة أسماء كل الأعمدة وعددها للتأكد
print(f"إجمالي عدد الأعمدة: {df_all_cols_sample.shape[1]}")
print("أسماء الأعمدة:", df_all_cols_sample.columns.tolist())

# عرض العينة
display(df_all_cols_sample)

✅ تم بنجاح! تم أخذ كل الأعمدة مع أول 5 صفوف فقط وحفظها في: 'nyc_all_features_first_5_rows.csv'
إجمالي عدد الأعمدة: 14
أسماء الأعمدة: ['RequestID', 'Boro', 'Yr', 'M', 'D', 'HH', 'MM', 'Vol', 'SegmentID', 'WktGeom', 'street', 'fromSt', 'toSt', 'Direction']

,RequestID,Boro,Yr,M,D,HH,MM,Vol,SegmentID,WktGeom,street,fromSt,toSt,Direction
0,20856,Queens,2015,6,23,23,30,9,171896,POINT (1052296.600156678 199785.26932711253),94 AVENUE,207 Street,Francis Lewis Boulevard,WB
1,21231,Staten Island,2015,9,14,4,15,6,9896,POINT (942668.0589509147 171441.21296926),RICHMOND TERRACE,Wright Avenue,Emeric Court,WB
2,29279,Bronx,2017,10,19,4,30,85,77817,POINT (1016508.0034050211 235221.59092266942),HUNTS POINT AVENUE,Whittier Street,Randall Avenue,NB
3,27019,Brooklyn,2017,11,7,18,30,168,188023,POINT (992925.4316054962 184116.82855457635),FLATBUSH AVENUE,Brighton Line,Brighton Line,NB
4,26734,Manhattan,2017,11,3,22,0,355,137516,POINT (1004175.9505178436 247779.63624949602),WASHINGTON BRIDGE,Harlem River Shoreline,Harlem River Shoreline,EB

In [24]:
import pandas as pd

# 1. قراءة الملف الأصلي أو عينة الملف لديك
input_file = 'archive/Automated_Traffic_Volume_Counts.csv' # أو اسم ملف العينة لو شغال عليه حالياً

# 2. تحديد أفضل الـ Features التي اتفقنا عليها فقط
best_features = [
    'Boro', 'Yr', 'M', 'D', 'HH', 'MM', 
    'Vol', 'SegmentID', 'WktGeom', 'Direction'
]

# قراءة الملف بالأعمدة المختارة فقط
df_cleaned = pd.read_csv(input_file, usecols=lambda col: col in best_features)

# 3. تنظيف البيانات السريع (حذف الصفوف التي بها قيم ناقصة في الأساسيات)
df_cleaned = df_cleaned.dropna(subset=['Boro', 'Yr', 'M', 'D', 'HH', 'Vol'])
df_cleaned = df_cleaned[df_cleaned['Vol'] >= 0]
df_cleaned = df_cleaned.drop_duplicates()

# 4. حفظ الملف النهائي النظيف
output_file = 'final_cleaned_traffic_data.csv'
df_cleaned.to_csv(output_file, index=False)

print(f"✅ تم تصفية وحفظ الملف بنجاح! إجمالي الأعمدة المختارة: {df_cleaned.shape[1]}")
print(df_cleaned.head())

✅ تم تصفية وحفظ الملف بنجاح! إجمالي الأعمدة المختارة: 10
            Boro    Yr   M   D  HH  MM  Vol  SegmentID  \
0         Queens  2015   6  23  23  30    9     171896
1  Staten Island  2015   9  14   4  15    6       9896
2          Bronx  2017  10  19   4  30   85      77817
3       Brooklyn  2017  11   7  18  30  168     188023
4      Manhattan  2017  11   3  22   0  355     137516

                                         WktGeom Direction
0   POINT (1052296.600156678 199785.26932711253)        WB
1      POINT (942668.0589509147 171441.21296926)        WB
2  POINT (1016508.0034050211 235221.59092266942)        NB
3   POINT (992925.4316054962 184116.82855457635)        NB
4  POINT (1004175.9505178436 247779.63624949602)        EB

In [ ]:
new = p